#!/usr/bin/env bash
#script does many things, from the #advanced

killer()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && killer' SIGTERM
	trap 'killer' SIGQUIT
done
