#!/usr/bin/env bash
# This script shows 12 hours and 59 minutes in it
hour=0
minute=1

while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
        printf "%d\n" $minute
        ((minute++))
    done
    minute=1
    ((hour++))
done

echo "Hour: $hour"
while [ $minute -lt 60 ]; do
    printf "%d\n" $minute
    ((minute++))
done
