#!/usr/bin/env bash
# This script displays 12 hours and each 59 minutes of the hour

h=0
while [ $h -le 12 ]
do
	echo "Hour: " $h
	m=1
	while [ $m -le 59 ]
	do
		echo $m
		m=$(( m+1 ))
	done
	h=$(( h+1 ))
done
