#!/usr/bin/env bash

# This script displays all active ipv4 addresses

ipv=$(ip addr show | grep -E '\binet\b.*\bbrd\b' | awk '{print $2}' | cut -d'/' -f1)

for ip in $ipv; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "$ip"
  fi
done
